### ISSUE TITLE
error with the execution of commands from MyCommand 

### ISSUE THREAD

**Issue by Iarkont** [nulli0n/nightcore-spigot#23]
All plugins that use nightcore have a problem: executing a command via config will throw an error if this command is made via MyCommand. 
Part of the error:
```
[18:59:38 ERROR]: Could not pass event InventoryClickEvent to nightcore v2.7.1
org.bukkit.command.CommandException: Unhandled exception executing command 'nmc' in plugin MyCommand v5.7.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
```

**Comment by nulli0n** [comment]
thats not a full log

**Comment by Iarkont** [comment]
I understood what the error was about: I incorrectly wrote one of the commands in config mycommand, which caused Nightcore to throw an error. There, even if one team is correct and the other is not, Nightcore will throw an error. Because of this, I could not immediately understand what the problem was, since when I entered the mycmd command directly, the error was not displayed. Sorry to trouble you
