### ISSUE TITLE
Error on console

### ISSUE THREAD

**Issue by pump61** [nulli0n/nightcore-spigot#24]
[11:20:46 WARN]: java.lang.NumberFormatException: For input string: "1F75FESlimeFrame Utils & Tools#C0C0C0" under radix 16
[11:20:46 WARN]:        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
[11:20:46 WARN]:        at java.base/java.lang.Integer.parseInt(Integer.java:662)
[11:20:46 WARN]:        at java.base/java.lang.Integer.decode(Integer.java:1450)
[11:20:46 WARN]:        at java.desktop/java.awt.Color.decode(Color.java:731)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.text.tag.TagUtils.colorFromHexString(TagUtils.java:19)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.text.tag.TagUtils.colorFromHexString(TagUtils.java:11)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.text.tag.impl.ShortHexColorTag.parse(ShortHexColorTag.java:25)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.text.tag.impl.ShortHexColorTag.parse(ShortHexColorTag.java:12)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.text.TextRoot.proceedTag(TextRoot.java:280)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.text.TextRoot.doJob(TextRoot.java:224)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.text.TextRoot.parse(TextRoot.java:158)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.text.TextRoot.parseIfAbsent(TextRoot.java:146)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.text.TextRoot.compile(TextRoot.java:62)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.text.NightMessage.create(NightMessage.java:36)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.text.NightMessage.create(NightMessage.java:31)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.text.NightMessage.asLegacy(NightMessage.java:91)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.text.NightMessage.asLegacy(NightMessage.java:104)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.ItemReplacer.packTrimmedLore(ItemReplacer.java:338)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.ItemReplacer.writeMeta(ItemReplacer.java:90)
[11:20:46 WARN]:        at ExcellentCrates-5.3.5.jar//su.nightexpress.excellentcrates.crate.menu.PreviewMenu.lambda$onAutoFill$10(PreviewMenu.java:172)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.menu.api.AutoFilled.getAutoFillItems(AutoFilled.java:50)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.menu.api.AutoFilled.autoFill(AutoFilled.java:29)
[11:20:46 WARN]:        at ExcellentCrates-5.3.5.jar//su.nightexpress.excellentcrates.crate.menu.PreviewMenu.onPrepare(PreviewMenu.java:111)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.menu.impl.AbstractMenu.open(AbstractMenu.java:168)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.menu.link.Linked.open(Linked.java:27)
[11:20:46 WARN]:        at ExcellentCrates-5.3.5.jar//su.nightexpress.excellentcrates.crate.CrateManager.previewCrate(CrateManager.java:401)
[11:20:46 WARN]:        at ExcellentCrates-5.3.5.jar//su.nightexpress.excellentcrates.crate.CrateManager.interactCrate(CrateManager.java:410)
[11:20:46 WARN]:        at ExcellentCrates-5.3.5.jar//su.nightexpress.excellentcrates.crate.listener.CrateListener.onCrateUse(CrateListener.java:96)
[11:20:46 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1246.execute(Unknown Source)
[11:20:46 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[11:20:46 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[11:20:46 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[11:20:46 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[11:20:46 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[11:20:46 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[11:20:46 WARN]:        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:593)
[11:20:46 WARN]:        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:549)
[11:20:46 WARN]:        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544)
[11:20:46 WARN]:        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:202)
[11:20:46 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1924)
[11:20:46 WARN]:        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51)
[11:20:46 WARN]:        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20)
[11:20:46 WARN]:        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55)
[11:20:46 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[11:20:46 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[11:20:46 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[11:20:46 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1546)
[11:20:46 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195)
[11:20:46 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[11:20:46 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1523)
[11:20:46 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1446)
[11:20:46 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[11:20:46 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1412)
[11:20:46 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1273)
[11:20:46 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
[11:20:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[11:20:46 WARN]: java.lang.NumberFormatException: For input string: "1F75FESlimeFrame Machines#C0C0C0" under radix 16
[11:20:46 WARN]:        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
[11:20:46 WARN]:        at java.base/java.lang.Integer.parseInt(Integer.java:662)
[11:20:46 WARN]:        at java.base/java.lang.Integer.decode(Integer.java:1450)
[11:20:46 WARN]:        at java.desktop/java.awt.Color.decode(Color.java:731)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.text.tag.TagUtils.colorFromHexString(TagUtils.java:19)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.text.tag.TagUtils.colorFromHexString(TagUtils.java:11)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.text.tag.impl.ShortHexColorTag.parse(ShortHexColorTag.java:25)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.text.tag.impl.ShortHexColorTag.parse(ShortHexColorTag.java:12)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.text.TextRoot.proceedTag(TextRoot.java:280)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.text.TextRoot.doJob(TextRoot.java:224)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.text.TextRoot.parse(TextRoot.java:158)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.text.TextRoot.parseIfAbsent(TextRoot.java:146)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.text.TextRoot.compile(TextRoot.java:62)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.text.NightMessage.create(NightMessage.java:36)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.text.NightMessage.create(NightMessage.java:31)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.text.NightMessage.asLegacy(NightMessage.java:91)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.text.NightMessage.asLegacy(NightMessage.java:104)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.ItemReplacer.packTrimmedLore(ItemReplacer.java:338)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.util.ItemReplacer.writeMeta(ItemReplacer.java:90)
[11:20:46 WARN]:        at ExcellentCrates-5.3.5.jar//su.nightexpress.excellentcrates.crate.menu.PreviewMenu.lambda$onAutoFill$10(PreviewMenu.java:172)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.menu.api.AutoFilled.getAutoFillItems(AutoFilled.java:50)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.menu.api.AutoFilled.autoFill(AutoFilled.java:29)
[11:20:46 WARN]:        at ExcellentCrates-5.3.5.jar//su.nightexpress.excellentcrates.crate.menu.PreviewMenu.onPrepare(PreviewMenu.java:111)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.menu.impl.AbstractMenu.open(AbstractMenu.java:168)
[11:20:46 WARN]:        at nightcore-2.7.2.jar//su.nightexpress.nightcore.menu.link.Linked.open(Linked.java:27)
[11:20:46 WARN]:        at ExcellentCrates-5.3.5.jar//su.nightexpress.excellentcrates.crate.CrateManager.previewCrate(CrateManager.java:401)
[11:20:46 WARN]:        at ExcellentCrates-5.3.5.jar//su.nightexpress.excellentcrates.crate.CrateManager.interactCrate(CrateManager.java:410)
[11:20:46 WARN]:        at ExcellentCrates-5.3.5.jar//su.nightexpress.excellentcrates.crate.listener.CrateListener.onCrateUse(CrateListener.java:96)
[11:20:46 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1246.execute(Unknown Source)
[11:20:46 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[11:20:46 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[11:20:46 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[11:20:46 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[11:20:46 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[11:20:46 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[11:20:46 WARN]:        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:593)
[11:20:46 WARN]:        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:549)
[11:20:46 WARN]:        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544)
[11:20:46 WARN]:        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:202)
[11:20:46 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1924)
[11:20:46 WARN]:        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51)
[11:20:46 WARN]:        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20)
[11:20:46 WARN]:        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55)
[11:20:46 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[11:20:46 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[11:20:46 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[11:20:46 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1546)
[11:20:46 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195)
[11:20:46 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[11:20:46 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1523)
[11:20:46 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1446)
[11:20:46 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[11:20:46 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1412)
[11:20:46 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1273)
[11:20:46 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
[11:20:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by nulli0n** [comment]
You didn't format color tag properly somewhere in your configs

**Comment by nulli0n** [comment]
Must be `<#1F75FE>` not `<#1F75FE`
