### ISSUE TITLE
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by RelicMelody** [nulli0n/nightcore-spigot#26]
`26.12 15:11:23 [Server] Server thread/FATAL Could not load 'plugins/nightcore-2.7.1.jar'
26.12 15:11:23 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
26.12 15:11:23 [Server] INFO at knot/org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:148) ~[Cardboard-1.21.jar:?]
26.12 15:11:23 [Server] INFO at knot/org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:1439) ~[paper-api-1.21.1-R0.1-20241021.162528-124.jar:?]
26.12 15:11:23 [Server] INFO at knot/org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:1356) ~[paper-api-1.21.1-R0.1-20241021.162528-124.jar:?]
26.12 15:11:23 [Server] INFO at knot/org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:1163) ~[paper-api-1.21.1-R0.1-20241021.162528-124.jar:?]
26.12 15:11:23 [Server] INFO at knot/org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:523) ~[Cardboard-1.21.jar:?]
26.12 15:11:23 [Server] INFO at knot/net.minecraft.class_3176.handler$zcf000$cardboard$init(class_3176.java:1286) ~[server-intermediary.jar:?]
26.12 15:11:23 [Server] INFO at knot/net.minecraft.class_3176.method_3823(class_3176.java:161) ~[server-intermediary.jar:?]
26.12 15:11:23 [Server] INFO at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:664) ~[server-intermediary.jar:?]
26.12 15:11:23 [Server] INFO at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
26.12 15:11:23 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
26.12 15:11:23 [Server] INFO Caused by: java.lang.ExceptionInInitializerError
26.12 15:11:23 [Server] INFO at su.nightexpress.nightcore.util.Version.loadComponents(Version.java:74) ~[?:?]
26.12 15:11:23 [Server] INFO at su.nightexpress.nightcore.util.Version.load(Version.java:67) ~[?:?]
26.12 15:11:23 [Server] INFO at su.nightexpress.nightcore.NightCore.<init>(NightCore.java:29) ~[?:?]
26.12 15:11:23 [Server] INFO at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
26.12 15:11:23 [Server] INFO at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
26.12 15:11:23 [Server] INFO at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
26.12 15:11:23 [Server] INFO at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
26.12 15:11:23 [Server] INFO at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
26.12 15:11:23 [Server] INFO at knot/org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:90) ~[Cardboard-1.21.jar:?]
26.12 15:11:23 [Server] INFO at knot/org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:144) ~[Cardboard-1.21.jar:?]
26.12 15:11:23 [Server] INFO ... 9 more`

Context:
I'm making a server for Cobblemon, and it's in Fabric, but I'm using Cardboard to use Paper/Spigot/Bukkit plugins work for the server. But I am running into an issue where I cannot seem to get Nightcore to work, or be identified. I cannot understand logs, so I was hoping I can find some help with this! We're trying to use the following Plugins:
- ExcellentCrates
- EconomyBridge
Just so you have more context on what plugins I'm using.

**Comment by nulli0n** [comment]
Modded servers are not supported.
