### ISSUE TITLE
Cannot find main class `su.nightexpress.combatpets.PetsPlugin'

### ISSUE THREAD

**Issue by FoGTeR** [nulli0n/nightcore-spigot#27]
[20:13:28 INFO]: [nightcore] [Core Components] ENTITY_ID_GENERATOR: Loaded
[20:13:28 INFO]: [nightcore] [Core Components] ITEM_NBT_COMPRESSOR: Loaded
[20:13:28 INFO]: [SpigotLibraryLoader] [LoneLibs] Loading 1 libraries... please wait
[20:13:29 INFO]: [SpigotLibraryLoader] [LoneLibs] Loaded library /home/ubuntu/limborgland/royalbattle/libraries/org/fusesource/jansi/jansi/2.4.1/jansi-2.4.1.jar
[20:13:29 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'CombatPets-2.3.1 (1).jar' in folder 'plugins/.paper-remapped'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `su.nightexpress.combatpets.PetsPlugin'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[paper-1.21.4.jar:1.21.4-53-326c687]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.21.4.jar:1.21.4-53-326c687]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.21.4.jar:1.21.4-53-326c687]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.21.4.jar:1.21.4-53-326c687]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.4.jar:1.21.4-53-326c687]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:561) ~[paper-1.21.4.jar:1.21.4-53-326c687]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:277) ~[paper-1.21.4.jar:1.21.4-53-326c687]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.21.4.jar:1.21.4-53-326c687]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-53-326c687]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.ClassNotFoundException: su.nightexpress.combatpets.PetsPlugin
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:529) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:508) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        ... 10 more

**Comment by nulli0n** [comment]
1. This is not CombatPets repo
2. Join discord if you have issues
