### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ProtoGhost** [nulli0n/nightcore-spigot#4]
[05:47:16 WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such column: dateCreated)
[05:47:16 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1179)
[05:47:16 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1190)
[05:47:16 WARN]:        at org.sqlite.core.DB.throwex(DB.java:1150)
[05:47:16 WARN]:        at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[05:47:16 WARN]:        at org.sqlite.core.NativeDB.prepare(NativeDB.java:126)
[05:47:16 WARN]:        at org.sqlite.core.DB.prepare(DB.java:264)
[05:47:16 WARN]:        at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:46)
[05:47:16 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:32)
[05:47:16 WARN]:        at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
[05:47:16 WARN]:        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:34)
[05:47:16 WARN]:        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:227)
[05:47:16 WARN]:        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:207)
[05:47:16 WARN]:        at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:327)
[05:47:16 WARN]:        at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
[05:47:16 WARN]:        at nightcore-2.5.2.1.jar//su.nightexpress.nightcore.database.sql.SQLQueries.executeStatement(SQLQueries.java:69)
[05:47:16 WARN]:        at nightcore-2.5.2.1.jar//su.nightexpress.nightcore.database.sql.executor.UpdateQueryExecutor.execute(UpdateQueryExecutor.java:71)
[05:47:16 WARN]:        at nightcore-2.5.2.1.jar//su.nightexpress.nightcore.database.AbstractDataHandler.update(AbstractDataHandler.java:148)
[05:47:16 WARN]:        at nightcore-2.5.2.1.jar//su.nightexpress.nightcore.database.AbstractUserDataHandler.saveUser(AbstractUserDataHandler.java:160)
[05:47:16 WARN]:        at nightcore-2.5.2.1.jar//su.nightexpress.nightcore.database.AbstractUserDataHandler.onSave(AbstractUserDataHandler.java:59)
[05:47:16 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[05:47:16 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[05:47:16 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[05:47:16 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[05:47:16 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[05:47:16 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by nulli0n** [comment]
Reset database.
