### ISSUE TITLE
[20:42:21 WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table lootconomy_users has no column named limitdata)

### ISSUE THREAD

**Issue by E1yu** [nulli0n/nightcore-spigot#9]
Shows up on playerjoin and leave

[20:42:21 WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table lootconomy_users has no column named limitdata)
[20:42:21 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1179)
[20:42:21 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1190)
[20:42:21 WARN]:        at org.sqlite.core.DB.throwex(DB.java:1150)
[20:42:21 WARN]:        at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[20:42:21 WARN]:        at org.sqlite.core.NativeDB.prepare(NativeDB.java:126)
[20:42:21 WARN]:        at org.sqlite.core.DB.prepare(DB.java:264)
[20:42:21 WARN]:        at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:46)
[20:42:21 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:32)
[20:42:21 WARN]:        at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
[20:42:21 WARN]:        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:34)
[20:42:21 WARN]:        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:227)
[20:42:21 WARN]:        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:207)
[20:42:21 WARN]:        at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:327)
[20:42:21 WARN]:        at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
[20:42:21 WARN]:        at nightcore-2.6.2.jar//su.nightexpress.nightcore.database.sql.SQLQueries.executeStatement(SQLQueries.java:69)
[20:42:21 WARN]:        at nightcore-2.6.2.jar//su.nightexpress.nightcore.database.sql.SQLQueries.executeStatement(SQLQueries.java:60)
[20:42:21 WARN]:        at nightcore-2.6.2.jar//su.nightexpress.nightcore.database.sql.executor.InsertQueryExecutor.execute(InsertQueryExecutor.java:51)
[20:42:21 WARN]:        at nightcore-2.6.2.jar//su.nightexpress.nightcore.database.AbstractDataHandler.insert(AbstractDataHandler.java:135)
[20:42:21 WARN]:        at nightcore-2.6.2.jar//su.nightexpress.nightcore.database.AbstractUserDataHandler.addUser(AbstractUserDataHandler.java:171)
[20:42:21 WARN]:        at nightcore-2.6.2.jar//su.nightexpress.nightcore.database.listener.UserListener.onUserLogin(UserListener.java:33)
[20:42:21 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor907.execute(Unknown Source)
[20:42:21 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[20:42:21 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[20:42:21 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:42:21 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[20:42:21 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[20:42:21 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[20:42:21 WARN]:        at net.minecraft.server.network.LoginListener.callPlayerPreLoginEvents(LoginListener.java:320)
[20:42:21 WARN]:        at net.minecraft.server.network.LoginListener$1.run(LoginListener.java:172)
[20:42:21 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[20:42:21 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[20:42:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by nulli0n** [comment]
Do a clean install.

**Comment by E1yu** [comment]
Hi, It is a clean install. Do you have support yet for purpur 1.20.4?
